### ISSUE TITLE
Demo app 2.5.x. misses swagger.json and some rest apis

### ISSUE THREAD

**Issue by Hilbrand** [openhab/openhab-distro#1045]
The demo app for the 2.5.x branch misses `rest/swagger.json`. It also misses the `/rest/extensions` (Visible in PaperUI as the menu entry Add-ons is missing) and seems to miss some other rest apis as well. I couldn't directly see why they were missing or is this intentional? I will continue looking into it, but if it's intentional of if someone has an idea that might cause this, that would be helpful.

**Comment by kaikreuzer** [comment]
Definitely not intentional!

**Comment by wborn** [comment]
> The demo app for the 2.5.x branch misses rest/swagger.json

Looks like the missing [provider-swagger](https://github.com/openhab/openhab-core/blob/857679f66b3db670f4f5bb80e834394c49d3dea4/features/karaf/openhab-tp/src/main/feature/feature.xml#L302-L306) takes care of providing it. I couldn't get it working easily. Maybe @maggu2810 knows how to get working in the IDE. But I'd rather see https://github.com/openhab/openhab-core/issues/726 fixed which will probably cause this to be reworked any way. :wink: 

> It also misses the /rest/extensions

This data is normally provided by `org.openhab.core.karaf` which is obviously Karaf only. We can add `org.openhab.core.extension.sample` so there is some sample data.

**Comment by wborn** [comment]
It helps to resolve these Swagger artifacts by adding them to an index. However it is depending on an old Guava version so the resolver fails because Bnd can't resolve multiple Guava versions:

`
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:4.3.0:export (default) on project org.openhab.demo.app: Unable to resolve <<INITIAL>>: missing requirement osgi.identity;filter:='(osgi.identity=com.eclipsesource.jaxrs.provider.swagger)' [caused by: Unable to resolve com.eclipsesource.jaxrs.provider.swagger version=1.1.1.201605111122: missing requirement osgi.wiring.package;filter:='(&(osgi.wiring.package=io.swagger.jaxrs.listing)(&(version>=1.5.7)(!(version>=2.0.0))))' [caused by: Unable to resolve io.swagger.jaxrs version=1.5.8: missing requirement osgi.wiring.package;filter:='(&(osgi.wiring.package=com.google.common.base)(&(version>=18.0.0)(!(version>=19.0.0))))']] -> [Help 1]
`

---

Newer Swagger versions do use a more recent Guava version. However they also use org.reflections that still depends on an old Guava version, e.g. with Swagger 1.6.0:

`
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:4.3.0:export (default) on project org.openhab.demo.app: Unable to resolve <<INITIAL>>: missing requirement osgi.identity;filter:='(osgi.identity=com.eclipsesource.jaxrs.provider.swagger)' [caused by: Unable to resolve com.eclipsesource.jaxrs.provider.swagger version=1.1.1.201605111122: missing requirement osgi.wiring.package;filter:='(&(osgi.wiring.package=io.swagger.jaxrs.listing)(&(version>=1.5.7)(!(version>=2.0.0))))' [caused by: Unable to resolve io.swagger.jaxrs version=1.6.0: missing requirement osgi.wiring.package;filter:='(&(osgi.wiring.package=org.reflections.scanners)(&(version>=0.9.0)(!(version>=1.0.0))))' [caused by: Unable to resolve org.reflections version=0.9.11: missing requirement osgi.wiring.package;filter:='(&(osgi.wiring.package=com.google.common.base)(&(version>=20.0.0)(!(version>=21.0.0))))']]] -> [Help 1]
`
