### ISSUE TITLE
Update of log4j2.xml does not trigger config update

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-distro#1187]
In OH2 when you updated org.ops4j.pax.logging.cfg the logging config would be updated immediately.  In OH3, when you update log4j2.xml, it is not detected.  "touch org.ops4j.pax.logging.cfg" forces a reread.  It looks like the xml needs to be added to the list to watch for updates.

https://github.com/openhab/openhab-distro/pull/1078 made the change to the xml.

**Comment by mhilbush** [comment]
@wborn Currently changes to the `log4j2.xml` file are picked up only when OH is restarted. Wondering if you considered adding the `monitorInterval` attribute to the `<Configuration>` tag in order to cause the configuration file to be reevaluated periodically? I added it to my file, and it seems to be working.

https://logging.apache.org/log4j/2.x/manual/configuration.html

**Comment by wborn** [comment]
Yes it also works fine for me @mhilbush! I also use it on other projects but I probably never added it in OH because I always configure logging via commands on the Console. :-)
