### ISSUE TITLE
NTP/Clock does not work in v1.6.2b 

### ISSUE THREAD

**Issue by jsprenkle** [openhab/openhab-distro#1253]
Platform information:

Hardware: RPI 3b+
OS: openhab flash image from github (openhabian-pi-raspios32-v1.6.2b.img  via  https://github.com/openhab/openhabian/releases)
openHAB version: openhabian-pi-raspios32-v1.6.2b.img.xz

I can’t get the openhab3 system clock set correctly.
The habpanel time widget shows the correct wall clock time.
If I open the front tail log monitor ( http://openhabiandevice.local:9001/ ) it shows 02:00 at 7:00pm.

The regional settings have a timezone set as “(GMT-6:00) US/Central”.
I’ve double checked the GPS coordinates of my location.

I assumed the NTP server was not configured so I installed it.

**Configuration**:
Hostname: time.google.com 
Refresh Interval: 60
NTP Refresh Frequency: 60
Server Port 123
Timezone (GMT-6:00) America/Chicago
I tried with no timezone set as well. No change was noticed.

All changes were made via the web interface.
The settings all look correct to me but it never shows NTP updates in the log.
The log showed network communication failures to 0.ntp.pool.org until it was changed to time.google.com
Rules triggered at 02:00 happen at 7pm wall clock time

**Comment by jsprenkle** [comment]
I fixed the issue in (openhabian-pi-raspios32-v1.6.3.img)
* use SSH or Putty to connect to the rpi
* Edit the  /etc/timezone file. You will need to use 'sudo' to edit system files. In my case it was "US/Central"
* use "sudo sync" to flush all changes to disk
* use "sudo reboot" to restart your system

issue: The openhab paperui panel does NOT set the /etc/timezone file

**Comment by mstormi** [comment]
When you run openHABian, please do not start installing stuff unless you're really really sure you need to do this
(usually you don't).
This is likely to break more than that it fixes. There *is* an ntp client active by default so now we cannot tell how it'll interact with your second one.
You should have run "openhabian-config" and used menu 1X to configure timezone.

BTW you should have opened this issue with openhab/openhabian, but now that your issue is fixed for the time being please close it.
