### ISSUE TITLE
OPENHAB 2 remove redundancy of installation addons

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab-distro#130]
I see three mechanisms to install addons.
1. the addon folder
2. the addon.cfg in conf/service
3. the Paper UI 

The first has it justification because it allows the installation of addons which are adapted to OH2.
The following two are redundant and one should be removed.

**Comment by xsnrg** [comment]
Maybe how I use all 3 will shed some light on why I think having the 3 options is okay.

First, if you are developing an addon, or want to try an addon before it is part of the main repository, having the addons folder is the way to do it.  You can swap it out and stay out of the maven repo jail.  There is a little bit of maintenance to do at the karaf shell to make sure you are running the version you want, but overall it is pretty clean and easy to use.

The paperUI method should exist because it is the easiest way for somebody new to OH2 to try out some bindings that might just work without having to do anything else.  It is the "oh, I have one of those devices" place that starts to bring out the real power of OpenHAB2 with discovery and configuration.

The cfg file is a place for power users that upgrade often.  Adding addons, extensions, UIs, etc to this file means that every time you update, or clear out the cache and tmp areas to force a full upgrade of the libraries and dependencies, you will make sure that your base set of addons remains constant.  Another advantage of the cfg configuration is the hands-off nature.  You can lock a configuration in and do not have to use a UI at all.

These are only my own use cases and experiences.  I use all 3 methods.

**Comment by Marty56** [comment]
Thanks for the reply. 
I am closing the issue.
