### ISSUE TITLE
Eclipse Installer: x509 certificate expired

### ISSUE THREAD

**Issue by karolinschlegel** [openhab/openhab-distro#1396]
When following the [installation guide](https://www.openhab.org/docs/developer/ide/eclipse.html), the warning in the following screenshot appears.
I'm not sure if this is related to openHAB or eclipse itself.
![image](https://user-images.githubusercontent.com/46576658/172584587-8ce620c4-6258-4fa3-9f9f-90c61a30fba8.png)

**Comment by wborn** [comment]
Trusting these certificates is specificially mentioned in step 8. of the [Eclipse IDE Setup instructions](https://www.openhab.org/docs/developer/ide/eclipse.html#eclipse-ide-setup):

> 8. Click Next> and Finish to start installation.
>
> During install accept licence agreement, "Unsigned Content" for Bndtools, and Eclipse Foundation certificates when requested to complete IDE installation.

This is an issue that cannot be fixed by openHAB. The respective 3rd party plugin developers should take care of providing/using properly signed bundles.

**Comment by karolinschlegel** [comment]
Hello @wborn,
thank you for the answer.
I have installed OpenHab via Eclipse before and know the error message you are referring to.
However, my issue here was that the certificate has expired since then. Accordingly, the error message is different from usual.
