### ISSUE TITLE
shrink default logfile size 

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-distro#1551]
To avoid file system fill issues particularly on resource-constrained system like Raspis, the***default** number and size of `openhab.log` and `events.log` should be cut to "much-less" like 1/10th of what it currently is.

Details see https://community.openhab.org/t/extensive-logging-of-binding-turns-filesystem-to-read-only/147405/14

**Comment by rkoshak** [comment]
I agree it should be much less than currently configured. But I think it's worth a little bit of analysis to determine something close to the right size.

How much logging does an average OH instance generate per day times the number of days worth of logging needed to diagnose and debug most OH problems plus a little extra . 

Obviously a default install events.log will fill up orders of magnitude faster than openhab.log so it makes sense to just focus on that and then size openhab.log the same.

It's just one data point but my events.log typically generates 4.2 MB per day. If we round that up add a bit of buffer lets say 6 MB.

Because these are text files, the compression is really good. I'm seeing a 12 MB log file being compressed to 866 KB (around 10% the original size). Given this, I wonder if it even matters how many log files we keep. The file actively being logged to is two orders of magnitude larger. But let's keep it in the calculation as every byte counts.

Based on my personal experience and experience helping users on the forum, two to three days is good enough to solve most problems but lets add another day as a buffer.

Currently the max space used should be around 54.4 MB assuming uniform compression of the older files:

    (16 MB + (16 MB * 7 files * .1)) * 2 = 54.4 MB

16 MB max file size plus seven backups at 10% original size times two for events.log and openhab.log.

If we use my setup as an average one (I think my events.log is pretty average) and the assumptions above:

   (6 MB + (6 MB * 4 files * .1)) * 2 = 16.8 MB

Given a data point of one, I'd recommend 6 MB as the file size and keeping four of the old ones. It's not 1/10th but still a pretty big reduction that I think will still support most use cases. More data points will only make the analysis better. If we want to make it tighter and go with 5 MB per day and drop it back to three days of old files:

   ( 5 MB + (5 MB * 3 files * .1)) * 2 = 13 MB

I don't know the savings of less than 4 MB is that great. 

If someone wants to do a separate analysis on openhab.log my system is not typical. A day's worth of openhab.log often fits on a single screen unless something has gone wrong.

**Comment by mstormi** [comment]
I was somewhat mistaken and had forgotten that all logs but the current one already get compressed.
That's not the case in quite some existing installations (including my own, which is why I forgot about it ;) ;) )
but in openhab-distro it _is_ the default.

So the projected savings in disk space we would get from implementing this is much less than I thought, thanks Rich for doing the math which made me remember that.
I believe the current default should be fine on RPis, too, so long story short, no need to shorten logs any further.
