### ISSUE TITLE
Add ZigBee, ZWave addon.xml data to /runtime/etc/addons.xml

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-distro#1622]
We have now successfully merged the USB serial suggestion finder service (for suggesting bindings that depend on USB serial devices); and consequently we also have added the discovery-methods to the addon.xml files for the ZigBee and Z-Wave bindings. The last step therefore is to include those two individual addon.xml files into the OH combined addons.xml file. But I don't know how to do that. => Any suggestions?

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

**Comment by J-N-K** [comment]
I have no idea. Especially since core is now limited to one file. Maybe the addon.xml of each individual add-on should be added as additional artifact (e.g. by using the [build-helper-maven-plugin](https://www.mojohaus.org/build-helper-maven-plugin/)) and the final XML is assembled in openhab-distro by aggregating them.

**Comment by andrewfg** [comment]
@J-N-K the strange thing is that the build process includes ZigBee and ZWave bindings in the overall main distro kar file, but does not include their addon.xml in the overall main addons.xml file.

**Comment by J-N-K** [comment]
That's not strange, because the aggregated addon.xml is assembled in openhab-addons, not on openhab-distro. In openhab-distro the file ist just copied to the right directory. Since zwave and ZigBee are in their own repositories, they are missing in openhab-addons and therefore missing in the addon.xml. The .kar is assembled in openhab-distro and contains all add-ons from the three repositories.

**Comment by andrewfg** [comment]
Closed via #1626
