### ISSUE TITLE
ItemRegistery(org.eclipse.smarthome.core.items.ItemRegistry) when channel is linked? 

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab-distro#218]
Hi,

I am running on Beta 3. It seems that the ItemRegistry and ItemChannelLinkRegistry's behavior changed.

Previously, when i accessed ItemRegistry when a channel  was linked  to an item, isLinked() method was called in BaseThingHandler(), and i could refer to itemRegistry to get the linked item. However, in Beta 3 (it seems), even a channel is linked, it is not guaranteed that i could find the linked item from itemRegistry. Is this as per designed? 

FYI. I realized that the linked item only added into itemRegistry after a channel within a thing is called. Is this normal? 

Thanks.

**Comment by kaikreuzer** [comment]
"isLinked" is called when a link is created - it is indeed not checked whether an item exists for it.

It should not matter though, since a binding must never access the itemRegistry.

P.S.: Such development questions should better go to the [ESH forum](https://www.eclipse.org/forums/index.php/f/271/).
