### ISSUE TITLE
Failed installing 'openhab-binding-"plcbus"' OH2

### ISSUE THREAD

**Issue by Men-O** [openhab/openhab-distro#303]
Fresh install win7 32bit and win7 64bit.
Failed installing 'openhab-binding-"plcbus"': No matching features for openhab-binding-"plcbus"/0.0.0

addons.cfg
remote = true
legacy = true

any version from : 
http://oss.jfrog.org/oss-snapshot-local/org/openhab/binding/org.openhab.binding.plcbus/1.9.0-SNAPSHOT/

**Comment by kaikreuzer** [comment]
PLCBus isn't listed here: http://docs.openhab.org/addons/1xaddons.html

So I do not understand how and why something could possibly trigger the installation of a non-existent Karaf feature...?

**Comment by Men-O** [comment]
Maybe because it was in openhab1 ?

**Comment by kaikreuzer** [comment]
Then please see here on how to deal with that: http://docs.openhab.org/developers/development/compatibilitylayer.html#how-to-use-openhab-1x-add-ons-that-are-not-part-of-the-distribution

**Comment by Men-O** [comment]
Okay,
Thanks for your patience.
These are my first steps into openhab, since i'm trying to move away from homeseer.
You may understand this is a bit too much at the moment to grasp.
i did copy openhab.cfg to the conf folder, but that didn't help,
so i guess there is some work to be done.
I guess i'll have to wait till someone takes a look at this.
In the mean time i will try to get an openhab1 setup done.
Thanks for clearing this up, at least i know now where it goes wrong.

**Comment by kaikreuzer** [comment]
Sorry, I didn't mean to blame you for not knowing the details - I don't want to scare away newbies!

When you are new, the safer way to start is probably OH1, since you will find most documentation for this, especially if you want to use OH1 bindings.

It seems that nobody so far looked into using plcbus on OH2, that's why it isn't available in the distro.
If you want to change it, please follow what is written on http://docs.openhab.org/developers/development/compatibilitylayer.html#how-to-use-openhab-1x-add-ons-that-are-not-part-of-the-distribution, i.e. put the binding in the addons folder (as you would do in OH1) and see if you can get it working.
