### ISSUE TITLE
Icons are missing in OH 2.x

### ISSUE THREAD

**Issue by Dom1n1c** [openhab/openhab-distro#307]
This affects the favicon.ico and the apple/app icons.
The icons seems to be missing in OH2, whereas OpenHAB 1.8.x had them.

https://community.openhab.org/t/site-icon/15729
https://community.openhab.org/t/favicon-in-oh2/15504

**Comment by kaikreuzer** [comment]
Actually, it is not that easy - the iOS images are definitely UI specific, that's why I asked [here](https://community.openhab.org/t/favicon-in-oh2/15504/4?u=kai) to enter them specifically for the Classic UI.
But what about the favicon? We could either also embed one per UI or we host it on Jetty at /favicon.ico globally (not completely sure how to best do this, though. As a servlet?)

**Comment by kaikreuzer** [comment]
Favicon is tracked as https://github.com/openhab/openhab-distro/issues/308
