### ISSUE TITLE
Automatic updates with ppa (Ubuntu 14.04)

### ISSUE THREAD

**Issue by Huaba** [openhab/openhab-distro#327]
I've installed openhab2-offline with the snapshot ppa. My system installs updates every night. After more updates openhab doesn't run without a complete system reboot. 

All UI's have an "ERR_CONNECTION_REFUSED" in the browser, and "sudo service openhab2 status" returns a "Ignoring predefined value for KARAF_HOME  - status: Not running..."

An "ps -ef | grep openhab" return a lot of running processes (actually 8).

Any hint to prevent this behavior for a openhab noob?

At the moment i've stopped the automatic updates for openhab with "sudo apt-mark hold openhab2", but this is only a workaround :)

Thx for your great work, i love Openhab!

Huaba

**Comment by abedwardsw** [comment]
@theoweiss i suspect this is because [init.d](https://github.com/openhab/openhab-linuxpkg/blob/master/resources/deb/etc/init.d/openhab2) scripts don't wait for the process to exit before returning control on issue of "stop".   If you'll notice that when you run openhab2 stop, the process is still running in most cases.

I see "stop" is called in some of the control scripts which appear to get called on upgrade of apt.   I see there is a sleep 5 in there, but wondering if that is long enough?

I think it might be an idea to modify the openhab2 init.d script to wait for the process to exit for say 20 seconds, then if it hasn't exited kill the process?   I think this might have better results.   I didn't test, but also assuming that "openhab2 restart" would have similar issues.

I could shoot you a pull request sometime next week if you want.

**Comment by BClark09** [comment]
Hi @Huaba, apologies for not getting back to you on this, it has been a busy time for deb packaging and we have moved the repo responsible for it, would you be able to copy this issue into [openhab-linuxpkg/issues](https://github.com/openhab/openhab-linuxpkg/issues) please? The behaviour might have changed since you posted this though, as I'd suspect that multiple instances are no longer allowed run at the same time. I should have time in the weekend to look at it.

**Comment by Huaba** [comment]
Done.
