### ISSUE TITLE
Sonos: org.eclipse.smarthome.binding.sonos:opmlUrl no more set

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#332]
It looks like the PR #305 ha suppressed the setting "org.eclipse.smarthome.binding.sonos:opmlUrl".
The result is that the Sonos binding is no more able by default to retrieve radio station names from tune-in.
Only an ultra expert user will be able to set manually the right value for this binding setting !

**Comment by kaikreuzer** [comment]
As org.eclipse.smarthome.binding.sonos was never the correct service id, I guess this has never worked, has it?

It should instead be binding.sonos.

**Comment by kaikreuzer** [comment]
I would hence claim that https://github.com/openhab/openhab-core/pull/78/files fixes this issue. If you agree, I will merge!

**Comment by lolodomo** [comment]
Yes please.

**Comment by maggu2810** [comment]
> As org.eclipse.smarthome.binding.sonos was never the correct service id, I guess this has never worked, has it?

IIRC org.eclipse.smarthome.binding.sonos has been used a long time but it has been changed by you 22 days ago:

https://github.com/eclipse/smarthome/commit/9f89d5245047c56ff4ca54356dac527886bc69e4#diff-60c5a5dd9ba40d50102d4d401509260eR11

**Comment by kaikreuzer** [comment]
Right, and I changed it because I noticed that updating binding configuration through the REST API didn't work (I tried that with the newly introduced callbackUrl), because the binding configs by default have a ["binding." service prefix](https://github.com/eclipse/smarthome/blob/6dd1df77136a70ec55da6746be05bf65b78ba15b/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/binding/BindingInfo.java#L28).
