### ISSUE TITLE
https doesn't work in IDE runtime

### ISSUE THREAD

**Issue by dvanherbergen** [openhab/openhab-distro#37]
When launching openHAB from within the IDE, https doesn't work.

**Comment by kaikreuzer** [comment]
Note that I did not manage to use the jetty.xml from https://github.com/openhab/openhab-distro/blob/master/distributions/distribution-resources/src/main/resources/userdata/etc/jetty.xml yet.
It would be ideal to configure the launch configuration in a way that it directly uses this file, so that we do not have to duplicate any jetty configuration.

**Comment by dvanherbergen** [comment]
Do you want to reuse the keystore also then?

**Comment by kaikreuzer** [comment]
Yes, would make sense.

**Comment by dvanherbergen** [comment]
In the distribution jetty config, it assumes that some configuration has already been done by pax-web. Because we don't use pax-web in the IDE, we cannot reuse the same jetty.xml configuration as in the distribution. So I fixed the https in the separate jetty.xml instead.
At this point, I'm thinking it would be better to leave the keystore separate as well. The one in the launch already contains a certificate, so the the jetty bundle doesn't need to be included in the launch, which prevents the keystore from always being marked as 'changed'.

**Comment by kaikreuzer** [comment]
ok, thanks!
