### ISSUE TITLE
Icon preference

### ISSUE THREAD

**Issue by sipvoip** [openhab/openhab-distro#382]
Icons in conf/icons/classic/ should have precedence over defaults.

https://community.openhab.org/t/solved-custom-icons/12228/23

**Comment by lolodomo** [comment]
Reading the code, it should be the case, custom icon provider has priority 5 compared to prority 0 for default icon provider.
I will test that.

**Comment by ThomDietrich** [comment]
I've already looked into the behavior there before:

https://github.com/openhab/openhab-docs/pull/250#discussion_r99584738

**Comment by lolodomo** [comment]
That's normal, if you overwrite an icon category, you have to do it fully, not just partially.
So for example, if you want to change switch category, you have to define all files relative to switch in conf/icons/classic. You cannot just replace switch-on.png for example.

**Comment by ThomDietrich** [comment]
Yes, that's what I'm saying :smiley:

**Comment by lolodomo** [comment]
So there is no bug and this issue can be closed.
Maybe the documentation should explain this point.

**Comment by ThomDietrich** [comment]
I would think so too. The Items article is the next one I'll rework completely. May just take a few more days to find the time for that.

If you are already looking at the code and would be able to do some modification the only thing I could think of is **logging**. Do you see any room for improvement wrt to the issue of wrongly named icons? Ideally users should be informed about violations of the icon naming rules, which is not always the case.

An example I've just tested is: I've defined an icon setting of "iPhone", which is not allowed due to uppercase. At this point no error is reported. As soon as I reload the BasicUI sitemap (without the file existing) I'll see the following exception:
```
2017-06-14 14:30:00.109 [WARN ] [eclipse.jetty.servlet.ServletHandler] - /icon/iPhone
java.lang.NullPointerException
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1488)[30:org.apache.commons.io:2.2.0]
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1465)[30:org.apache.commons.io:2.2.0]
...
```

After adding a file `icons/classic/iPhone.svg` the exception is gone, an icon is still not shown in the sitemap but no error is reported in the log. That can't be the ideal solution...

**Comment by lolodomo** [comment]
No idea where is coming from your NPE.

For your second point, I don't know which version you are running but in the recent snapshots, there is now the following debug log when the icon category is not found: Requested icon category xxx provided by no icon provider; try to failback to category "none".

Reading the code, my feeling is that there is a little bug with lowercase/uppercase, If you have defined as icon in your item or sitemap a name containing an uppercase character like "iPhone", first there will be a search for iphone.svg (search of category). Then when getting the icon depending on the state, there is apparently no conversion to lowercase, that means the searched file is iPhone-on.svg for example and if not found iPhone.svg is searched.

I will test and debug.

**Comment by lolodomo** [comment]
I submitted a PR that fixed a potential bug with case and add a new debug log: "Use icon toto.svg as toto-value.svg is not found". So this log will appear when your item state does not match an icon in your iconset.

**Comment by lolodomo** [comment]
In fact, it is possible to define icon category with uppercase characters in your item or sitemap files but the icons file names must be in lowercase. So "Switch" or "SWITCH" are valid and can be used indifferently but require files named switch.svg / switch.png.

**Comment by ThomDietrich** [comment]
Thanks for looking into the issue. I've provoked the described behavior with Build #945. I don't know there the npe comes from but I'm afraid it lurks around somewhere... Do you need more details from me?

**Comment by lolodomo** [comment]
Please wait for the next build that will include my change and then try again.
If you have still the problem, please open an issue in the ESH repo explaining how to reproduce the problem with the demo sitemap.

**Comment by ThomDietrich** [comment]
Will do. See ya.
