### ISSUE TITLE
Parameters removed from binding cfg files persist in userdata/config even after restart

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-distro#396]
The relevant thread on the forums is here:

https://community.openhab.org/t/help-im-ready-to-give-up/20006/93

The issue particularly impacts 1.9 bindings like Weather, MQTT, and HTTP where there can be repeated copies of one or more setting type (e.g. more than one broker config for MQTT, more than one weather location in Weather, more than one URL to cache in HTTP).

If, for example, a user decided they no longer need to poll a certain URL with the HTTP binding and remove it from their conf/services/http.cfg file, that parameter does not get removed from the corresponding userdata/config/org/openhab/http.config.

Even upon a reboot, the removed parameters persist in the userdata/config version.

As a user I expect updates to the services/binding.cfg file to apply, including additions, modifications, and removals.

If this is the wrong repo (e.g. this is really an ESH problem) let me know and I'll repost it there.

Thanks

**Comment by watou** [comment]
See also:

* https://community.openhab.org/t/what-is-effect-of-dosgi-clean-in-karaf/6320
* https://github.com/openhab/openhab-distro/issues/77

**Comment by AngelosF** [comment]
Maybe a solution would be to remove the userdata/config/org/openhab/*.config file whenever a user changes the respective services/*.cfg file and let OH2 recreate it?

**Comment by AngelosF** [comment]
I found something related...

Modifications to `/etc/openhab2/services/addons.cfg` end up in 2 destinations:
`/var/lib/openhab2/config/org/openhab/addons.config`
AND
`/var/lib/openhab2/etc/org.openhab.addons.cfg`

Both files within $OPENHAB_USERDATA subfolders suffer from the same issue (stale configs not being updated)

Example: In my `/etc/openhab2/services/addons.cfg`:
```
package = expert
remote = true
legacy = false
binding = knx1,zwave,mqtt1,weather1,samsungtv,astro,ntp,wol1
ui = basic,paper,habpanel,habmin
persistence = mapdb,influxdb
action = mail
transformation = map,regex,jsonpath
#voice =
misc = restdocs,homekit
```

In `/var/lib/openhab2/config/org/openhab/addons.config`:
```
action="mail"
binding="knx1,zwave,mqtt1,weather1,samsungtv,astro,ntp,wol1"
felix.fileinstall.filename="file:/var/lib/openhab2/etc/org.openhab.addons.cfg"
inding="knx1,zwave,mqtt1,weather1,samsungtv,astro,ntp"
legacy="false"
misc="restdocs,homekit"
package="expert"
persistence="mapdb,influxdb"
remote="true"
service.pid="org.openhab.addons"
transformation="map,regex,jsonpath"
ui="basic,paper,habpanel,habmin"
voice=""
```
Note the `inding=` line coming from an older wrong edit.
This file will be recreated after I delete it and restart OH2 (2.2.0 S981)

While in `/var/lib/openhab2/etc/org.openhab.addons.cfg`:
```
package = expert
ui = basic,paper,habpanel,habmin
misc = restdocs,homekit
remote = true
action = mail
binding = knx1,zwave,mqtt1,weather1,samsungtv,astro,ntp,wol1
persistence = mapdb,influxdb
transformation = map,regex,jsonpath
voice = 
legacy = false
inding = knx1,zwave,mqtt1,weather1,samsungtv,astro,ntp
```
Last line is wrong and it is kept from an older wrong edit of addons.cfg
This file will NOT be recreated after delete and OH2 restart...

**Comment by kaikreuzer** [comment]
> As a user I expect updates to the services/binding.cfg file to apply, including additions, modifications, and removals.

While I agree that this is the expected behavior for anyone who exclusively does configuration through cfg files (like OH1 users), this would not be valid in general as configurations could be entered through other ways (console commands, UIs, etc.).

The current service (ConfigDispatcher) merely reads config files and adds the content to the central configuration.

In OH1 there was no issue, because OSGi was always started with the "clean" option, meaning that it completely wiped all its configuration on a start, so there was never outdated data.

What do you think would be the best solution here? Maybe we should introduce some "marker" in the cfg files that tells the ConfigDispatcher whether this should be considered an "exclusive" configuration or not. If it is exclusive, all other entries for the same service would be deleted.

> If this is the wrong repo (e.g. this is really an ESH problem) let me know 

Actually yes, it is an ESH topic; but as the "history" and the main impact is on openHAB side, let's first discuss our requirements here.

**Comment by AngelosF** [comment]
marker sounds good....

so, we would have an "exclusive = yes" (defaulted to yes if not set?) option in every `$OPENHAB_CONF/services/*.cfg` file that would wipe clean the existing service config and apply the cfg file contents/parameters.

If someone wants to keep existing service configs, s/he would set this to `no`.

**Comment by davidgraeff** [comment]
It is not a wise idea to add a convention like the marker line, because people wouldn't expect this and wouldn't know about it. We want to make it simpler, not more complicated.

It had this problem in the MqttService, too. Some broker connections might be configured via text files, others via the GUI. Should I allow the GUI to remove or alter a textual configured broker connection? If I configure a broker connection with the same ID in text files and the GUI, which one takes precedence?

I decided to solve this with a flag in the broker connection. If the textual configured flag is set, the GUI is not allowed to alter/remove. Textual configured brokers take precedence over GUI configured ones.

My suggestion is to apply this idea to the ConfigDispatcher as well. It needs to distinguish between textual and GUI key-value configuration tuples. Textual configured key-value pairs take precedence over GUI ones. The GUI should "disable" or "hide" options, that are already configured textual, maybe with a small hint.

**Comment by kaikreuzer** [comment]
Let's continue the discussion at https://github.com/eclipse/smarthome/pull/3988, so that we have a single place for it.

**Comment by kaikreuzer** [comment]
@rkoshak & @AngelosF: Good news, the issue should be fixed in the latest openHAB Distro!

Any cfg-file which contains `pid:org.openhab.xxxx` as a first line will now be considered exclusively for settings for the given pid. Any old entries should thus be removed by the runtime.

May I ask you to create PRs for the cfg files that should be adapted in openhab1-addons? Especially the ones you mentioned above like weather, mqtt & http - thanks!

**Comment by ThomDietrich** [comment]
The line including a line explaining its meaning should be commented by default, correct?

**Comment by ssalonen** [comment]
@kaikreuzer @thomdietrich : it looks there is still some issues with openHAB2 and modbus binding at least, see comments here https://github.com/openhab/openhab1-addons/issues/5084#issuecomment-386384606

By reading this issue I am not sure what the user needs to enter to configuration. Was there pull request done for some binding already?
