### ISSUE TITLE
Wrong redirection when behind a reverse proxy server

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-distro#423]
When smarthome is behind a reverse proxy server that only allows https, the redirection from https://host/ is improperly going to http://host/start/index. This is happening because the 302 redirect is ignoring the X-Forwarded-Proto header. See https://community.openhab.org/t/nginx-redirect-to-port-80/16760/6 for more details.

According to @kaikreuzer, the redirection is occurring at https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/runtime/etc/jetty.xml#L42-L50

**Comment by kaikreuzer** [comment]
Did you manage to figure out what needs to be changed in the Jetty configuration to solve this problem?

**Comment by jeffsf** [comment]
As noted, https://www.example.com/exposed/path/ sends the browser to http://www.example.com/start/index

From what I can tell, the source from openhab-master `launch/home/etc/jetty.xml` causes a redirect, rather than a rewrite

    <New class="org.eclipse.jetty.rewrite.handler.RedirectRegexRule">
      <Set name="regex">/$</Set>
      <Set name="replacement">/start/index</Set>
    </New>

Unfortunately, it also appears that this is "compiled in" and is not present in `/var/lib/openhab2/etc/jetty.xml`

**Comment by kaikreuzer** [comment]
> Unfortunately, it also appears that this is "compiled in" and is not present in /var/lib/openhab2/etc/jetty.xml

No, this is exactly the file you can find in  https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/runtime/etc/jetty.xml.

If you have a solution, please provide a PR for it.

**Comment by jeffsf** [comment]
I've banged at this for a while, and haven't found a quick solution. If someone else takes a stab at it, here's what I've found so far:

My nginx reverse proxy is properly inserting/modifying the headers

- Host
- X-Real-IP
- X-Forwarded-For
- X-Forwarded-Proto

In the default configuration, a `GET / HTTP/1.1` request results in openHAB returning
```
HTTP/1.1 302 Found
Date: Wed, 15 Mar 2017 01:13:47 GMT
Location: http://www.example.com/start/index
Connection: close
Server: Jetty(9.2.19.v20160908)
```
which, as noted is _not_ correct.

If the proxy is configured to redirect http to https, it _appears_ to work to the end user, but only because the redirect to http handled at the proxy.

Working with a dev build, changing `jetty.xml` to replace the redirect with a rewrite
```
- <New class="org.eclipse.jetty.rewrite.handler.RedirectRegexRule">
+ <New class="org.eclipse.jetty.rewrite.handler.RewriteRegexRule">
```
results in Jetty returning a 404 (Not found) a body that indicates it was for `/start/index`

I'll confirm again when I get back to this, but it did not appear that the result was any different when I replaced the "custom" logic around the `X-Forwarded-Scheme` with the current Jetty-ism of 
```
<Call name="addCustomizer">
  <Arg>
    <New class="org.eclipse.jetty.server.ForwardedRequestCustomizer" />
  </Arg>
</Call>
```
http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/server/ForwardedRequestCustomizer.html
which states there
> This customizer looks at at HTTP request for headers that indicate it has been forwarded by one or more proxies. Specifically handled are
> 
> Forwarded, as defined by rfc7239
> - X-Forwarded-Host
> - X-Forwarded-Server
> - X-Forwarded-For
> - X-Forwarded-Proto
> - X-Proxied-Https
> If these headers are present, then the Request object is updated so that the proxy is not seen as the other end point of the connection on which the request came

I did just notice that the "custom" config looked for `X-Forwarded-Scheme` and not `X-Forwarded-Proto` I have not tried that change yet, nor do I know if I added the ForwardedRequestCustomizer in the proper place.

**Comment by stefan-muc** [comment]
Can confirm it's still present in openHAB 2.4.0
If you use non-standard ports and need a workaround and you are using nginx, add this to your server configuration:
`error_page 497 =301 https://$host:$server_port$request_uri;`
This will do a 301 (or 302 when you like that better) redirect to the HTTPS url.

See https://community.openhab.org/t/openhab-with-nginx-redirects-https-to-http/63109 for screenshots and details.

**Comment by BClark09** [comment]
> This is happening because the 302 redirect is ignoring the X-Forwarded-Proto

> I did just notice that the "custom" config looked for X-Forwarded-Scheme and not X-Forwarded-Proto I have not tried that change yet.

You were right here, it looks like Jetty is using two different headers instead of the rfc7239 defined `X-Forwarded-Proto`... try setting both headers in your proxy configuration for now e.g:

```nginx
location / {
  proxy_pass                          http://localhost:8080/;
  proxy_set_header Host               $http_host;
  proxy_set_header X-Real-IP          $remote_addr;
  proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto  $scheme;
  proxy_set_header X-Forwarded-Scheme $scheme;
}
```

**Comment by BClark09** [comment]
I believe the issue is caused by lines [26](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/runtime/etc/jetty.xml#L26) and [35](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/runtime/etc/jetty.xml#L35) of `/$OPENHAB_RUNTIME/etc/jetty.xml`. Changing these to `X-Forwarded-Proto` instead of `X-Forwarded-Scheme` means that you do not ned to set the latter header as an extra, and @jeffsf's original nginx configuration would work as expected.

**Comment by stefan-muc** [comment]
> `X-Forwarded-Proto`... try setting both headers in your proxy configuration for now

I did this and can confirm it's working with OpenHAB 2.4.0
So I [proposed a change to documentation ](https://github.com/openhab/openhab-docs/pull/858) so we have a working configuration for released version.

**Comment by stefan-muc** [comment]
> I believe the issue is caused by lines [26](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/runtime/etc/jetty.xml#L26) and [35](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/runtime/etc/jetty.xml#L35) of `$OPENHAB_RUNTIME/etc/jetty.xml`. Changing these to `X-Forwarded-Proto` instead of `X-Forwarded-Scheme` means that you do not need to set the latter header as an extra, and @jeffsf's original nginx configuration would work as expected.

You are right, I changed these lines (reverted my nginx config) and redirect now works as expected.
I will make a pull request for this change
