### ISSUE TITLE
Add persistence.mongodb 1.x addon to distro

### ISSUE THREAD

**Issue by AngelosF** [openhab/openhab-distro#487]
I don't know what has to be done with regards to PR to include this bundle in the distribution, so I open up this issue.

This 1.x persistence service bundle was recently tested and it was found to work on openHAB2 (no exact release info available)

1.11.0 snapshot was downloaded from:
```
https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/persistence/org.openhab.persistence.mongodb/target/
```

Installed manually in the addons folder and configured using:
http://docs.openhab.org/addons/persistence/mongodb/readme.html
http://docs.openhab.org/configuration/persistence.html

Community thread: https://community.openhab.org/t/mongodb-persistence-with-openhab-2/31949

User reported that it is working.  I haven't tested this myself.

**Comment by kaikreuzer** [comment]
As mentioned in the linked thread, the exact steps that need to be done are explained here: http://docs.openhab.org/developers/development/compatibilitylayer.html#how-to-add-a-successfully-tested-1x-add-on-to-the-distribution

If anything is unclear and you prefer to create a placeholder issue instead of a PR, please do so in the openhab1-addons repo!

**Comment by AngelosF** [comment]
forget it :)
