### ISSUE TITLE
Unstable OH2 does not start with APT-GET package

### ISSUE THREAD

**Issue by msfunty** [openhab/openhab-distro#506]
Hi,

with the most current unstable version OH2 does not start anylonger.
Some configuration or missing files/directories is misleading.

In syslog:
`start.sh[326]: mkdir: cannot create directory ‘/usr/share/openhab2/userdata/tmp’: Datei oder Verzeichnis nicht gefunden`

And also after creating that directory manually it's still not successful:
`start.sh[326]: karaf: KARAF_BASE is not valid: /usr/share/openhab2/userdata
systemd[1]: openhab2.service: main process exited, code=exited, status=1/FAILURE`

That failure does not occur with the stable version.

**Comment by kaikreuzer** [comment]
Sounds like a problem with the linuxpkg (apt), so please report at https://github.com/openhab/openhab-linuxpkg/issues - thanks!

**Comment by BClark09** [comment]
Since the snapshots of OH2 linuxpkg no longer use

>start.sh[326]

I'd actually suggest the [community forum](https://community.openhab.org/c/setup-configuration-and-use/installation) first.

Things to try:

 - Make sure systemd is using the `/usr/lib/systemd/system/openhab2.service` file, and that it contains [these](https://github.com/openhab/openhab-linuxpkg/blob/master/resources/systemd/openhab2.service) contents.
 - If using your own service file for whatever reason, make sure it contains the `environment=OPENHAB_*` paths as shown [again, here](https://github.com/openhab/openhab-linuxpkg/blob/master/resources/systemd/openhab2.service).
