### ISSUE TITLE
Error installing on debian 8

### ISSUE THREAD

**Issue by danhuss** [openhab/openhab-distro#515]
I'm not sure if this is the right place to report this, but I'm trying to install on a fresh Debian 8 VM and running into issues right from the start following the documentation. Running the command to add the apt-key I get `gpg: no valid OpenPGP data found.` Interestingly I can get around it by telling wget to ignore certificate errors, but then apt-get update errors out on the openhab repo and I can't get past that.

**Comment by ThomDietrich** [comment]
Imho this issue is neither related to bintray, openHAB or Debian 8. The error is quite common and mostly related to a proxy server or another special network connection (possibly related to your VM env).

Ignoring the error is one approach, the better would be to teach your system a set of certificates with `sudo apt install ca-certificates`

Please verify your setup and let us know if there is more to it than I suggested. Thanks!

**Comment by danhuss** [comment]
*facepalm*

Thanks, that did it...
