### ISSUE TITLE
Library Bundles Not Cosistent with Eclipse IDE

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab-distro#610]
Hi
I am developing some add-ons that require certain eclipse libraries like org.eclipse.jetty.proxy. It exist in Eclipse IDE but when I deploy the AddOn to OpenHab-dist server, it complains that the required import bundle does not exist. How do I force openhab-dist to download these libraries? Thanks

**Comment by splatch** [comment]
Hey @lsafelix75,
It's your duty to deliver all necessary libraries to runtime in order to get your plugin working. As you found - Eclipse is different than openhab distro. I don't know what is your addon and how its being developed, but for openhab 2 you can use karaf features mechanism.

There is an old article about that. Despite of passed time it is still relevant: https://davidvaleri.wordpress.com/2010/08/13/combining-karaf-features-pax-url-and-maven-to-deploy-a-plain-jar-as-an-osgi-bundle/
If you are interested in more upt o date documentation and additional details you can check official documentation: https://karaf.apache.org/manual/latest/#_provisioning

Cheers,
Lukasz

**Comment by lsafelix75** [comment]
@splatch  Thanks. I try to limit the number of libraries to be imported manually. org.eclipse.jetty.proxy is a common and standard package which can be found or detected automatically by Eclipse IDE and also OpenhabHab 2.1 release but not those nightly distro. Openhab uses different version of org..eclipse.jetty for each build  (now it is 9.3.25) and i don't want to manually add outdated org.eclipse.jetty.proxy to my addon that could cause issue later.

That is the reason i asked this question- there is inconsistencies of libraries included in each repo. Some of these (standard) libraries could be left out intentionally or forgot to include for each nightly repo.

**Comment by splatch** [comment]
If you are interested in jetty Karaf re-uses pax-web (https://github.com/ops4j/org.ops4j.pax.web) project and changes in presence of jetty proxy module might come from changes in it. OpenHab 2.1 if I remember correctly is baded on Karaf 4.0.x while 2.2 is already on Karaf 4.1.x. Both use different versions of pax web and jetty.
If you could confirm how did you get it OH 2.1 (which module depends on it) we could check what happened. OH used to have some jetty customizations before but now it rely on pax-web.

**Comment by lsafelix75** [comment]
@splatch. Thanks for the explanation.
When I go through /usr/share/openhab2/system ... I could see all the libraries in there which include jetty.proxy.jar . But, why can't Karaf console discover this library when I run my bundle? I did specify #import requirement but Karaf fails to look for the required .jar though it exist within  openhab repo.

**Comment by splatch** [comment]
Eclipse uses different "runtime provisioning" than Karaf. Even if both of them are called "features" the underlying mechanism is completely different. Eclipse uses P2 (Provisioning v2 which is successor of simple provisioning based on site.xml file) which wraps metadata from project modules into requirements and capabilities. Reason why you can see jetty proxy packages in IDE is because some of modules declares such dependency in `MANIFEST.MF`.
Karaf mechanism is based on "feature.xml" files which consist bundle URLs as well as simple dependency declarations. It does not work with requirements per say, however these are being evaluated during installation time by OSGi framework. This gives you a complete control over what will end up in runtime, however this simplicity bring costs in maintainability.

A general rule - manual copying of file to system directory doesn't help unless you install it manually. If you miss `org.eclipse.jetty.proxy` package then install bundle which contains it via `install` command. Only one required argument is bundle URL - which can be file, http or mvn (if you rely on maven coordinates). You can also drop JAR/bundle into deploy or addons folder - it will be picked up automatically for you and used after restart. You can also force refresh of dependant bundles, however this is thing which might not always be as reliable as we would expect.

Try `find /usr/share/openhab2/system -name "*.xml" -print -exec grep -C 3 "jetty.proxy" {} \;` or `jetty/proxy`, or just `jetty`. This should show which feature descriptor brought some of jetty jars into system directory. Console way, which you most likely know, is `list|grep -i jetty`.

If your binding is new and you provide a new dependency then it needs to be explicitly declared in feature descriptors in order to let it be installed together with your addon.

**Comment by lsafelix75** [comment]
@splatch. this is a very good explanation. thank you so much

**Comment by lsafelix75** [comment]
@splatch you mentioned ' force refresh ' and 'install' command. I assume 'install' is Karaf console command, how about force refresh?

**Comment by splatch** [comment]
> you mentioned ' force refresh ' and 'install' command. I assume 'install' is Karaf console command, how about force refresh?

Yes I meant karaf console commands. There is also `refresh <bundle-id>` command which allows to reload module imports without making an update check - it literally just attempts to reload classes. However, if your module is in failed state then you can just try `start` command as there is nothing to flush.

**Comment by lsafelix75** [comment]
@splatch . OK, i tried your method by using find to look for bundle and i got the following output. Question is i see some repo have dependencies for the bundle (jetty.proxy) that i need. When i try to install the depend bundle, lets say "install mvn:org.eclipse.jetty/jetty-proxy/9.3.15.v20161220", i am getting whole bunch of depencies error for jetty-proxy. Appreciate you can give some directions. Thanks

> pi@orangepilite:/usr/share/openhab2/runtime$ find /usr/share/openhab2/runtime/system -name "*.xml" -print -exec grep -C 3 "jetty-proxy" {} \;
> /usr/share/openhab2/runtime/system/org/ops4j/pax/web/pax-web-features/6.0.7/pax-web-features-6.0.7-features.xml
> /usr/share/openhab2/runtime/system/org/ops4j/pax/web/pax-web-features/6.0.7/pax-web-features-6.0.7-jettyconfig.xml
> /usr/share/openhab2/runtime/system/org/eclipse/smarthome/config/org.eclipse.smarthome.config.xml
> grep: /usr/share/openhab2/runtime/system/org/eclipse/smarthome/config/org.eclipse.smarthome.config.xml: Is a directory
> /usr/share/openhab2/runtime/system/org/eclipse/smarthome/core/org.eclipse.smarthome.core.thing.xml
> grep: /usr/share/openhab2/runtime/system/org/eclipse/smarthome/core/org.eclipse.smarthome.core.thing.xml: Is a directory
> /usr/share/openhab2/runtime/system/org/eclipse/smarthome/core/org.eclipse.smarthome.core.binding.xml
> grep: /usr/share/openhab2/runtime/system/org/eclipse/smarthome/core/org.eclipse.smarthome.core.binding.xml: Is a directory
> /usr/share/openhab2/runtime/system/org/apache/karaf/features/standard/4.1.3/standard-4.1.3-features.xml
> /usr/share/openhab2/runtime/system/org/apache/karaf/features/framework/4.1.3/framework-4.1.3-features.xml
> /usr/share/openhab2/runtime/system/org/openhab/distro/distro-kar/2.2.0/distro-kar-2.2.0-features.xml
>         <bundle dependency="true">mvn:org.eclipse.jetty/jetty-http/9.3.15.v20161220</bundle>
>         <bundle dependency="true">mvn:org.eclipse.jetty/jetty-util/9.3.15.v20161220</bundle>
>         <bundle dependency="true">mvn:org.eclipse.jetty/jetty-io/9.3.15.v20161220</bundle>
>         <bundle dependency="true">mvn:org.eclipse.jetty/jetty-proxy/9.3.15.v20161220</bundle>
>         <bundle dependency="true">mvn:org.eclipse.jetty.websocket/websocket-api/9.3.15.v20161220</bundle>
>         <bundle dependency="true">mvn:org.eclipse.jetty.websocket/websocket-common/9.3.15.v20161220</bundle>
>         <bundle dependency="true">mvn:org.eclipse.jetty.websocket/websocket-client/9.3.15.v20161220</bundle>
> /usr/share/openhab2/runtime/system/org/openhab/distro/distro/2.2.0/distro-2.2.0-features.xml
>         <bundle dependency="true">mvn:org.eclipse.jetty/jetty-http/9.3.15.v20161220</bundle>
>         <bundle dependency="true">mvn:org.eclipse.jetty/jetty-util/9.3.15.v20161220</bundle>
>         <bundle dependency="true">mvn:org.eclipse.jetty/jetty-io/9.3.15.v20161220</bundle>
>         <bundle dependency="true">mvn:org.eclipse.jetty/jetty-proxy/9.3.15.v20161220</bundle>
>         <bundle dependency="true">mvn:org.eclipse.jetty.websocket/websocket-api/9.3.15.v20161220</bundle>
>         <bundle dependency="true">mvn:org.eclipse.jetty.websocket/websocket-common/9.3.15.v20161220</bundle>
>         <bundle dependency="true">mvn:org.eclipse.jetty.websocket/websocket-client/9.3.15.v20161220</bundle>
> /usr/share/openhab2/runtime/system/org/openhab/distro/openhab-addons/2.2.0/openhab-addons-2.2.0-features.xml
> /usr/share/openhab2/runtime/system/org/openhab/distro/overrides/2.2.0/overrides-2.2.0-features.xml

**Comment by lsafelix75** [comment]
@splatch . What is the best way of handling dependencies automatically like my case? I mean what do i need to include to my POM.xml, plugins.xml or MANIFEST.MF so that whenever i install my new Openhab bundle, it automatically resolves those dependecies like download from somewhere or use maven? Cheers

**Comment by kaikreuzer** [comment]
The documentation how to include 3rd party libs is at https://www.eclipse.org/smarthome/documentation/development/bindings/dependencies.html#3rd-party-libraries.
For any other discussion I would suggest to use the discussion forum.
