### ISSUE TITLE
Chart-Width in BasicUI too small

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab-distro#665]
The default chart looks not very nice in BasicUI:

![image](https://user-images.githubusercontent.com/20517474/37862619-50c8519a-2f50-11e8-8f6c-cf0cc3fcf837.png)

It would be good to have 100% width as it is done for an Image-Item. This was also a change that I did request in the past. This looks now very nice and is responsive (Android-App as well):

![image](https://user-images.githubusercontent.com/20517474/37862643-b358a4ea-2f50-11e8-9bb1-bc1b87cbe4a8.png)

Thanks
Michael

**Comment by kaikreuzer** [comment]
Afair, @resetnow did this on purpose in order to avoid too pixelated charts - so it is a feature, not a bug.
To circumvent this, we should rather think about including vector-based charts in the Basic UI, which would look much nicer.
Anyhow, please note that the Basic UI is a part of ESH, so the right issue tracker is https://github.com/eclipse/smarthome/issues.

**Comment by michaeljoos72** [comment]
@kaikreuzer Yesterday I saw this setting in PaperUI:

![image](https://user-images.githubusercontent.com/20517474/37945928-0a3a8f92-3183-11e8-95da-7e2c38c4b170.png)

But it doesn't change anything for a chart in a sitemap. Is this a setting for an upcoming change for vector-based charts?
