### ISSUE TITLE
All things gone after java OutOfMemory 

### ISSUE THREAD

**Issue by rzwarts74** [openhab/openhab-distro#702]
I recently had to restart my MacBook which runs OH2.2.0 release build. Unfortunately all my "things" were gone. So I now have to re-add them again. Is there a way to maybe put this back in file format (as I am kinda clueless as where they reside currently). 

Just to be clear I am running in "simple" mode where linking is done automatically. 

And obviously there is a memory leak somewhere as Java was 2.4GB big... and no longer responding.

Any help is much appreciated (also if this is the wrong place).

**Comment by wborn** [comment]
There is a [community topic](https://community.openhab.org/t/how-to-find-the-cause-of-a-outofmemoryerror-in-oh2/24874?u=wborn) on how to troubleshoot OutOfMemory exceptions @rzwarts74.

Perhaps you can also retest if the memory leak has been fixed with openHAB 2.3.0 which was released this week?

You can also define Things in .things files as is outlined in the [Things documentation](https://www.openhab.org/docs/configuration/things.html#defining-things).

**Comment by wborn** [comment]
We're at 2.4.0 nowadays. So if it is still an issue with that release please leave a comment.
