### ISSUE TITLE
Persistence passwords in logfile

### ISSUE THREAD

**Issue by CrispinP** [openhab/openhab-distro#762]
Hello,

I shut down my mySQL DB today for some maintenance on the hardware and notice this in the OH logs files;

`17:20:54.198 [ERROR] [ysql.internal.MysqlPersistenceService] - mySQL: Failed connecting to the SQL database using: driverClass=com.mysql.jdbc.Driver, url=jdbc:mysql://10.10.50.185:3306/openhab2, user=openhab2, password=blablablas`

Passwords should not be logged to log file. Any way this could be masked?

This is 2.3 stable build on RPi

thanks

**Comment by martinvw** [comment]
The ideal place to report it would be https://github.com/openhab/openhab1-addons/ because that where this class lives, what would you think would give the right balance between userfriendly and not exposing too much:

- display nothing about the password
- display the number of starts the password has characters
- remove the center part of the password and show only the first and last characters.

**Comment by martinvw** [comment]
@CrispinP any further thoughts about?
