### ISSUE TITLE
After removing a jar from addons and restarting OH2, the bundle is still installed

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#77]
Maybe that is the expected behaviour but that is something we have to know.
Suppressing a jar file from the addons sub-directory seems to not uninstall a binding.
When I run bundle:list, I see that my bundle is still installed.

Running "bundle:uninstall 166" uninstalled the binding.

**Comment by maggu2810** [comment]
This is expected behaviour (at least for me). Putting a file into this directory leads to install it. Removing the file does not trigger an uninstall.

**Comment by kaikreuzer** [comment]
Well, it is unexpected for any openHAB 1 user, because there the osgi container is always started with "clean" and hence addons are installed on every startup, if present.
I would at least suggest to add this to the docu of the addons folder at https://github.com/openhab/openhab-distro/blob/master/docs/sources/getting-started.md#installation.

**Comment by kaikreuzer** [comment]
Also related to https://community.openhab.org/t/what-is-effect-of-dosgi-clean-in-karaf/6320

**Comment by lolodomo** [comment]
So what are we doing for that ? Do you want just a sentence to explain the point in https://github.com/openhab/openhab-docs/blob/gh-pages/installation/index.md ?

**Comment by maggu2810** [comment]
If this is not the expected behavior - and its already clear that it is for the ones that are using the feature for OH1 and expect the same one for the openHAB-distro, then adding some information to the documentation is perhaps a good idea.
