### ISSUE TITLE
start.sh fails on (at least) debian packages if called directly

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-distro#772]
See https://community.openhab.org/t/oh2-3-fails-to-start/52064/3

As that's not documented (or as it may be but people didn't read it, at least I couldn't find it), I believe we can avoid a number of people to run into trouble if we check the startup/user environment we're in before proceeding.

I think unrelated but just for completeness if you choose to touch start.sh anyway, see also #120.

**Comment by BClark09** [comment]
Hi @mstori, since this is an issue that effects the DEB or RPM packages could you place an issue in https://github.com/openhab/openhab-linuxpkg /issues/ ?

This happens because the environment variables that specify where each folder is aren't set yet.

We can override/replace these scripts in the package to correct this.

**Comment by BClark09** [comment]
I think the wrong issue was closed here. Can we close this issue in favor of https://github.com/openhab/openhab-linuxpkg/issues/125?
