### ISSUE TITLE
High memory and CPU usage?

### ISSUE THREAD

**Issue by steilerDev** [openhab/openhab-distro#862]
Hi,

I am running openHAB inside a docker container (using the official openHAB docker), but since I think this issue is related to openHAB, rather than the docker bundling, I am opening the issue here.

I am experiencing a very high memory and CPU usage after some time of running openHAB (according to `docker stats`, openHAB requires 1.5GB of memory and has a CPU utilization of 190%).

The main issue is, due to the high stress on the system, the instance starts to become unreliable and finally unusable and a restart of the docker is necessary to operate the system. This usually takes about 2 to 4 days until a restart is necessary.

I am not sure if this is a known phenomenon/scenario, or if this is a result of misconfiguration or even a memory leakage bug. Unfortunately I don't know which configurations files/debugger can help to narrow the issue down, therefore please let me know which metrics/configuration files/etc. you need to better understand the issue.

Thanks!

Frank

**Comment by wborn** [comment]
You could update to openHAB 2.4.0 which fixes several memory leaks (if you haven't already).

Otherwise you can enable `-XX:+HeapDumpOnOutOfMemoryError` as JVM startup parameter and analyze the heap dump. See also [How to find the cause of a OutOfMemoryError in OH2?](https://community.openhab.org/t/how-to-find-the-cause-of-a-outofmemoryerror-in-oh2/24874?u=wborn)

Another way to get a heap dump is by issuing the `dev:dump-create` command in the [Console](https://www.openhab.org/docs/administration/console.html#the-console).

```
openhab> dev:dump-create
Created dump zip: 2018-12-15_105726.zip
```

It creates a zip file (in your userdata dir) which contains the heap dump as the `heapdump.hprof` file. 
If you know it runs out of memory after 3 days you could run `dev:dump-create` after 2.5 days. Then it should be obvious in the heap dump where the memory is leaking.

**Comment by steilerDev** [comment]
Hi @wborn,

I already updated to 2.4.0. I also created a dump file, but unsure what the best way to examine it is.

However I think I found the issue. I developed a Homebridge plugin to integrate openHAB, that used `SSE` extensively by subscribing to `http://<openhab-host>/rest/events?topics=smarthome/items/<habItem>/statechanged`. In total I had about 60 of those subscriptions active. After reducing this to a single subscription channel (subscribing to `http://<openhab-host>/rest/events?topics=smarthome/items/` and filtering only relevant items) I haven't experienced the memory leak and complete shutdown anymore. I am not sure if this is an openHAB issue or more an Eclipse Smarthome issue, since I didn't find any documentation on this feature in openHAB.

What are your thoughts?

Thanks,

Frank

**Comment by wborn** [comment]
> In total I had about 60 of those subscriptions active

That may indeed consume some memory especially if events are not delivered. Did you also test if the issue was resolved by increasing the max allocated Java memory with `-Xmx`?

I know in 2.3.0 there were SSE memory leaks and @lolodomo fixed these see:
* https://github.com/eclipse/smarthome/issues/4809
* https://github.com/eclipse/smarthome/pull/5910

If this is still an issue you can create one in the openhab-core [issue tracker](https://github.com/openhab/openhab-core/issues) (the openHAB fork of ESH).

**Comment by steilerDev** [comment]
I will create an issue in openhab-core, in order to see if that is something, that should be investigated further. Thank you!

**Comment by lolodomo** [comment]
By the way, @steilerDev is not using REST sitemap SSE subscriptions, so it has no link with the mentioned issues which were relative to SSE for UI only.
