### ISSUE TITLE
Broken network binding for 2.4 - please make note in tutorial

### ISSUE THREAD

**Issue by robbieh** [openhab/openhab-distro#887]
Reference: https://community.openhab.org/t/confirmed-not-fully-functional-network-binding-2-4-does-not-work/61265/2

I spent way too long today trying to work through the tutorial and figure out why I couldn't get the network binding to do anything. After trying to increase the log level and then trying numerous fixes, I found that reference above. If this is really broken this badly, please put a note into the tutorial. Or withdraw 2.4. Or something. Having an important part of the tutorial depend on a broken component is very frustrating.

**Comment by Hilbrand** [comment]
The documentation for the network binding is in another repository. Feel free to add the note to the documentation so others can be helped. Here is a link to the documentation page to edit: https://github.com/openhab/openhab2-addons/edit/master/addons/binding/org.openhab.binding.network/README.md

**Comment by davidgraeff** [comment]
Can this be closed?

**Comment by wborn** [comment]
Is this issue about the tutorial using the Network Binding in an [example](https://www.openhab.org/docs/tutorial/configuration.html) which doesn't work with 2.4.0 @robbieh ? 

> As soon as you click on "Network Binding", the binding will start an automatic discovery of all (reachable) network devices in the same subnet as your openHAB installation resides in via ICMP (ping).

That's a known issue fixed in 2.5.0, see https://github.com/openhab/openhab2-addons/issues/4559. Although it might help to add a note to the tutorial about this.

Or is this issue about add-on configuration files having the wrong content for some reason? That would be an issue for all add-ons and is not specific to the Network Binding.

**Comment by wborn** [comment]
Let's close this issue since hasn't been any reply and it's in the wrong repository.
