### ISSUE TITLE
Invalid http context id at startup

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#891]
At startup of the snapshot 1556, I got this warning:
```
10:53:26.355 [WARN ] [d.internal.element.HttpContextElement] - Registered http context [null] did not contain a valid http context id
```
This was already the case in some recent previous snapshots.

**Comment by GadgetAngel** [comment]
At startup of snapshot 1556, I get this warning also:

`[WARN ] [.internal.element.HttpContextElement] - Registered http context [null] did not contain a valid http context id`

**Comment by davepee** [comment]
Me too

**Comment by gnalbandian** [comment]
Hi. I'm at snapshot 1583 and also getting the same at startup

`20:39:28.647 [WARN ] [d.internal.element.HttpContextElement] - Registered http context [null] did not contain a valid http context id`

**Comment by servim** [comment]
#1588
2019-05-10 17:22:17.801 [WARN ] [.internal.element.HttpContextElement] - Registered http context [null] did not contain a valid http context id

**Comment by kaikreuzer** [comment]
I've identified this log message to be coming from the bundle `pax-web-extender-whiteboard`, which we actually do not need (as we are not using whiteboard pattern for Jetty). I assume that this bundle was introduced by some recent Karaf upgrade.

@wborn & @maggu2810: Any good suggestion how we can get rid off it? Do we have to introduce the "ignore" in the distro packaging again or is there a more elegant way?

**Comment by maggu2810** [comment]
Is this message raised on registration of a http servlet?
Which one?

**Comment by maggu2810** [comment]
https://github.com/ops4j/org.ops4j.pax.web/blob/c83adac/pax-web-extender-whiteboard/src/main/java/org/ops4j/pax/web/extender/whiteboard/internal/element/ListenerMappingWebElement.java#L89

The message seems to be caused by a non null but empty (after trimmed) context ID.
Wouldn't it be much simpler to use a "valid" context ID?

**Comment by maggu2810** [comment]
There is a `ServletContextHelperTracker` and a `HttpContextTracker`.

* The `ServletContextHelperTracker` is using the service property `osgi.http.whiteboard.context.name` of the respective service for the context ID.
* The `HttpContextTracker` is using the service property `httpContext.id` (of Pax Web Extender constants) of the respective service for the context ID.

So it seems to be annoying to see this message if whiteboard is not used at all. 

In our case it is triggered by the component implementation `org.eclipse.smarthome.io.http.internal.SmartHomeHttpContext`.
We could add the service property `httpContext.id` to set an ID for the HTTP context that is used as an ID for "Pax Web Extender".
Sure, this is a specific consumer property but it does not harm to add that property and perhaps it is simpler then changing log levels or modifying the Karaf features (replacement XML).

**Comment by maggu2810** [comment]
I have given it a try. It works, we can get rid of that message this way.

**Comment by kaikreuzer** [comment]
Thanks for the analysis. Ok, it works, but it still feels like some workaround.
I was just wondering, if we can deactivate HttpContext whiteboard support completely - after all, we [did the same for the HttpServlet whiteboard support](https://github.com/openhab/openhab-util/blob/master/pax-web-patch/src/main/java/org/openhab/patch/ClassAdapter.java#L22) (iirc) as it caused use performance issues for us.

**Comment by maggu2810** [comment]
Please ping me if I should create the PR for openHAB Core.
IMHO we should allow the usage of the whiteboard pattern.

**Comment by kaikreuzer** [comment]
Yes, to allow it in general, it makes sense to adapt openhab-core this way, I agree.

**Comment by maggu2810** [comment]
Hm, let's wait a moment.

**Comment by maggu2810** [comment]
Sorry... No need to wait. All fine :wink:

**Comment by davidgraeff** [comment]
Ehm. Is there a document listing all the patches done to libraries? That pax-web patch is a bit surprising for someone not involved in the years old discussion ^^

**Comment by maggu2810** [comment]
Which years old discussion are you refering to? Or do you mean to this discussion in a few years?
Isn't the commit message a really good documentation for "why a change has been done"?

If I find some spare time, I will discuss that topic with "Pax Web" why a warning is logged if the OSGi spec does not state that this property needs to be present and is a special Pax Web property.
After that we will see if we can remove this property because "Pax Web" has been changed or if there is a valid general reason.

**Comment by davidgraeff** [comment]
A commit message is kind of a documentation. But not the starter documentation I would have in mind that I hand to someone that want's to start with core development.

At the moment if someone wants to exploit httpservlet whiteboard pattern, because we are using Karaf and it should be enabled by default, that person will spend hours on hours try to find out why his code does not work and will never assume that we have patched pax-web and just disabled this functionality.

**Comment by maggu2810** [comment]
Sorry, I don't understand.

1. What does not work? We are discussion about a log message only.
2. Who patches Pax Web and who is using a patched Pax Web bundle?
3. That's about an extender (from Pax Web POV) for a HTTP context and not about the whiteboard pattern for servlets.

**Comment by davidgraeff** [comment]
Could be that I missunderstood this comment:

> I was just wondering, if we can deactivate HttpContext whiteboard support completely - after all, **we did the same for the HttpServlet whiteboard** support (iirc) as it caused use performance issues for us.

**Comment by maggu2810** [comment]
Sorry, I was not aware that you reffering to the patch that has been mentioned by Kai.
My understanding has been that you refer to the changes I have done to get rid of that log message.

In my distros I do not use `openhab/openhab-util` with its Pax Web patch and I would prefer openHAB Distro would stop using that approach.

That's not my part. :wink:

**Comment by maggu2810** [comment]
Can you point me to the location this utility / patch is applied?

**Comment by maggu2810** [comment]
Hm, let's answer it myself:

* https://github.com/openhab/openhab-distro/blob/fc655c815c480c9b607c4eccb520b5a618f62448/distributions/openhab/pom.xml#L59-L71
* https://github.com/openhab/openhab-distro/blob/fc655c815c480c9b607c4eccb520b5a618f62448/distributions/openhab/pom.xml#L140-L158
